import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-sm border p-8 md:p-12">
        <Link href="/" className="inline-flex items-center text-sm text-gray-500 hover:text-primary mb-8">
           <ArrowLeft className="w-4 h-4 mr-1" /> Back to Calculator
        </Link>
        
        <h1 className="text-3xl font-bold text-gray-900 mb-6">Terms & Conditions</h1>
        
        <div className="prose prose-blue max-w-none text-gray-600 space-y-4">
          <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>
          
          <h3 className="text-gray-900">1. Acceptance of Terms</h3>
          <p>
            By accessing and using the SalaryCal India In-Hand Salary Calculator, you acknowledge and agree to be bound by these Terms and Conditions. If you do not agree to these terms, please discontinue using this website immediately.
          </p>

          <h3 className="text-gray-900">2. Educational and Informational Purpose</h3>
          <p>
            This calculator is designed for <strong>educational and informational purposes only</strong>. The calculations provided are estimates based on generic salary structures and the current Indian Income Tax laws for the financial year 2025-26. Actual deductions, allowances, and tax implications may vary based on individual circumstances.
          </p>
          
          <h3 className="text-gray-900">3. No Professional Financial or Tax Advice</h3>
          <p>
            The results generated by this tool do <strong>not</strong> constitute professional financial advice, tax advice, or legal advice. We strongly recommend consulting with a qualified Chartered Accountant (CA), tax advisor, or financial planner for accurate tax planning, investment strategies, and filing recommendations tailored to your specific situation.
          </p>

          <h3 className="text-gray-900">4. Accuracy Disclaimer</h3>
          <p>
            While we make reasonable efforts to maintain accurate tax information and calculation logic based on the latest Finance Act and tax regulations, we make no representations or warranties of any kind—express or implied—about the completeness, accuracy, reliability, or suitability of the calculator or the information provided. Tax laws change frequently, and your actual tax liability may differ from the estimates provided.
          </p>

          <h3 className="text-gray-900">5. User Responsibility</h3>
          <p>
            You are responsible for verifying all information entered and the results obtained. The calculator should not be used as a substitute for professional consultation. Always consult with a qualified tax professional before making financial or tax-related decisions.
          </p>

          <h3 className="text-gray-900">6. Limitation of Liability</h3>
          <p>
            In no event shall SalaryCalc India, its owners, operators, or developers be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, this website or the calculator, including but not limited to loss of data, loss of profits, business interruption, or any other commercial damages, even if we have been advised of the possibility of such damages.
          </p>

          <h3 className="text-gray-900">7. Use License</h3>
          <p>
            You are granted a limited, non-exclusive, non-transferable license to use this website for personal, non-commercial purposes only. You may not reproduce, distribute, transmit, modify, or use this calculator's code or content for any commercial purpose without explicit written permission.
          </p>

          <h3 className="text-gray-900">8. Modifications to Service</h3>
          <p>
            We reserve the right to modify, update, or discontinue this calculator at any time without prior notice. We are not liable for any modifications, suspension, or discontinuance of this service.
          </p>

          <h3 className="text-gray-900">9. Third-Party Links</h3>
          <p>
            This website may contain links to third-party websites. We are not responsible for the accuracy, completeness, or legality of external sites. Accessing third-party links is at your own risk, and we are not liable for any damages arising from such links.
          </p>

          <h3 className="text-gray-900">10. Changes to Terms</h3>
          <p>
            We may update these Terms and Conditions at any time. Changes will be effective immediately upon posting. Your continued use of the website constitutes your acceptance of the updated terms. Please review these terms periodically for changes.
          </p>

          <h3 className="text-gray-900">11. Governing Law</h3>
          <p>
            These Terms and Conditions are governed by the laws of India. You agree to submit to the jurisdiction of the courts in India for any disputes arising from or related to this website.
          </p>

          <h3 className="text-gray-900">12. Contact Information</h3>
          <p>
            For questions about these Terms and Conditions, please contact us at <a href="mailto:support@salarycalc.in" className="text-primary hover:underline">support@salarycalc.in</a>.
          </p>
        </div>
      </div>
    </div>
  );
}
